# Домашнее задание № 2. Мешок слов

# Задание 1 (3 балла)

In [ ]:
У векторайзеров в sklearn есть встроенная токенизация на регулярных выражениях. Найдите способо заменить её на кастомную токенизацию

Обучите векторайзер с дефолтной токенизацией и с токенизацией razdel.tokenize. Обучите классификатор с каждым из векторизаторов. Сравните метрики и выберете победителя.

(в вашей тетрадке должен быть код обучения и все метрики; если вы сдаете в .py файлах то сохраните полученные метрики в отдельном файле или в комментариях)

In [55]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity

from IPython.display import Image
from IPython.core.display import HTML 

In [35]:
import re
from collections import Counter
text = '''Верблюдов-то за что? Дебилы, бл...
",
"Хохлы, это отдушина затюканого россиянина, мол, вон, а у хохлов еще хуже. Если бы хохлов не было, кисель их бы придумал.
",
"Собаке - собачья смерть.
",
"Страницу обнови, дебил. Это тоже не оскорбление, а доказанный факт - не-дебил про себя во множественном числе писать не будет. Или мы в тебя верим - это ты и твои воображаемые друзья?
",
"тебя не убедил 6-страничный пдф в том, что Скрипалей отравила Россия? Анализировать и думать пытаешься? Ватник что ли?)
'''
regex = re.compile('(?u)\\b\\w\\w+\\b')
tokens = re.findall(regex, text.lower())
vocab = sorted(set(tokens))
counts = Counter(tokens)
counts = [counts[key] for key in sorted(counts.keys())]
print(pd.DataFrame([counts], columns = vocab))

   анализировать  бл  будет  бы  было  ватник  верблюдов  верим  во  вон  ...  \
0              1   1      1   2     1       1          1      1   1    1  ...   

   том  ты  убедил  факт  хохлов  хохлы  хуже  числе  что  это  
0    1   1       1     1       2      1     1      1    3    3  

[1 rows x 60 columns]


In [38]:
from razdel import tokenize
text = '''Верблюдов-то за что? Дебилы, бл...
",
"Хохлы, это отдушина затюканого россиянина, мол, вон, а у хохлов еще хуже. Если бы хохлов не было, кисель их бы придумал.
",
"Собаке - собачья смерть.
",
"Страницу обнови, дебил. Это тоже не оскорбление, а доказанный факт - не-дебил про себя во множественном числе писать не будет. Или мы в тебя верим - это ты и твои воображаемые друзья?
",
"тебя не убедил 6-страничный пдф в том, что Скрипалей отравила Россия? Анализировать и думать пытаешься? Ватник что ли?)
'''
list(tokenize(text))

[Substring(0, 12, 'Верблюдов-то'),
 Substring(13, 15, 'за'),
 Substring(16, 19, 'что'),
 Substring(19, 20, '?'),
 Substring(21, 27, 'Дебилы'),
 Substring(27, 28, ','),
 Substring(29, 31, 'бл'),
 Substring(31, 34, '...'),
 Substring(35, 36, '"'),
 Substring(36, 37, ','),
 Substring(38, 39, '"'),
 Substring(39, 44, 'Хохлы'),
 Substring(44, 45, ','),
 Substring(46, 49, 'это'),
 Substring(50, 58, 'отдушина'),
 Substring(59, 69, 'затюканого'),
 Substring(70, 80, 'россиянина'),
 Substring(80, 81, ','),
 Substring(82, 85, 'мол'),
 Substring(85, 86, ','),
 Substring(87, 90, 'вон'),
 Substring(90, 91, ','),
 Substring(92, 93, 'а'),
 Substring(94, 95, 'у'),
 Substring(96, 102, 'хохлов'),
 Substring(103, 106, 'еще'),
 Substring(107, 111, 'хуже'),
 Substring(111, 112, '.'),
 Substring(113, 117, 'Если'),
 Substring(118, 120, 'бы'),
 Substring(121, 127, 'хохлов'),
 Substring(128, 130, 'не'),
 Substring(131, 135, 'было'),
 Substring(135, 136, ','),
 Substring(137, 143, 'кисель'),
 Substring(144, 146,

In [ ]:
razdel.tokenize делит на токены и индексы, а векторайзер в sklearn подсчитывает частотность употребления.

# Задание 2 (3 балла)

In [ ]:
Преобразуйте таблицу с абсолютными частотностями в семинарской тетрадке в таблицу с tfidf значениями. (Таблица - https://i.ibb.co/r5Nc2HC/abs-bow.jpg) Формула tfidf есть в семинаре на картнике с пояснениями на английском. Считать нужно в питоне. Формат итоговой таблицы может быть любым, главное, чтобы был код и можно было воспроизвести вычисления.

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["я и ты", "ты и я", "я, я и только я", "только не я", "он"]
vectorizer = CountVectorizer()
vectorizer.fit(text)
print(vectorizer.vocabulary_)
vector = vectorizer.transform(text)
print(vector.toarray())

{'ты': 3, 'только': 2, 'не': 0, 'он': 1}
[[0 0 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 0 0]]


In [61]:
print("IDF of: ")
n_docs = len(corpus)   
idf = {}

for w in words_set:
    k = 0    # number of documents in the corpus that contain this word
    
    for i in range(n_docs):
        if w in corpus[i].split():
            k += 1
            
    idf[w] =  np.log10(n_docs / k)
    
    print(f'{w:>15}: {idf[w]:>10}' )

IDF of: 
              я: 0.6989700043360189
            Он.: 0.6989700043360189
             не: 0.6989700043360189
             я.: 0.2218487496163564
             Ты: 0.6989700043360189
             Я,: 0.6989700043360189
              и: 0.2218487496163564
         Только: 0.6989700043360189
              Я: 0.6989700043360189
         только: 0.6989700043360189
            ты.: 0.6989700043360189


# Задание 3 (2 балла)

In [ ]:
Обучите 2 любых разных классификатора из семинара. Предскажите токсичность для текстов из тестовой выборки (используйте одну и ту же выборку для обоих классификаторов) и найдите 10 самых токсичных для каждого из классификаторов. Сравните получаемые тексты - какие тексты совпадают, какие отличаются, правда ли тексты токсичные?

Требования к классификаторам:
а) один должен использовать CountVectorizer, другой TfidfVectorizer
б) у векторазера должны быть вручную заданы как минимум 5 параметров
в) у классификатора должно быть задано вручную как минимум 2 параметра
г) f1 мера каждого из классификаторов должна быть минимум 0.75

In [23]:
data = pd.read_csv('labeled.csv')
data.head()

comment  toxic
0               Верблюдов-то за что? Дебилы, бл...\n    1.0
1  Хохлы, это отдушина затюканого россиянина, мол...    1.0
2                          Собаке - собачья смерть\n    1.0
3  Страницу обнови, дебил. Это тоже не оскорблени...    1.0
4  тебя не убедил 6-страничный пдф в том, что Скр...    1.0

In [24]:
data.toxic.value_counts(normalize=True)

0.0    0.66514
1.0    0.33486
Name: toxic, dtype: float64

In [25]:
train, test = train_test_split(data, test_size=0.1, shuffle=True)

In [26]:
train.reset_index(inplace=True)
test.reset_index(inplace=True)

In [53]:
from sklearn.feature_extraction.text import CountVectorizer


text = ['''Верблюдов-то за что? Дебилы, бл...
",
"Хохлы, это отдушина затюканого россиянина, мол, вон, а у хохлов еще хуже. Если бы хохлов не было, кисель их бы придумал.
",
"Собаке - собачья смерть.
",
"Страницу обнови, дебил. Это тоже не оскорбление, а доказанный факт - не-дебил про себя во множественном числе писать не будет. Или мы в тебя верим - это ты и твои воображаемые друзья?
",
"тебя не убедил 6-страничный пдф в том, что Скрипалей отравила Россия? Анализировать и думать пытаешься? Ватник что ли?)
''']

vectorizer = CountVectorizer()
vectorizer.fit(text)

print(vectorizer.vocabulary_)


vector = vectorizer.transform(text)
print(vector.shape)
print(vector.toarray())

{'верблюдов': 6, 'то': 48, 'за': 18, 'что': 58, 'дебилы': 12, 'бл': 1, 'хохлы': 55, 'это': 59, 'отдушина': 30, 'затюканого': 19, 'россиянина': 38, 'мол': 25, 'вон': 9, 'хохлов': 54, 'еще': 17, 'хуже': 56, 'если': 16, 'бы': 3, 'не': 27, 'было': 4, 'кисель': 22, 'их': 21, 'придумал': 34, 'собаке': 42, 'собачья': 43, 'смерть': 41, 'страницу': 44, 'обнови': 28, 'дебил': 11, 'тоже': 49, 'оскорбление': 29, 'доказанный': 13, 'факт': 53, 'про': 35, 'себя': 39, 'во': 8, 'множественном': 24, 'числе': 57, 'писать': 33, 'будет': 2, 'или': 20, 'мы': 26, 'тебя': 47, 'верим': 7, 'ты': 51, 'твои': 46, 'воображаемые': 10, 'друзья': 14, 'убедил': 52, 'страничный': 45, 'пдф': 32, 'том': 50, 'скрипалей': 40, 'отравила': 31, 'россия': 37, 'анализировать': 0, 'думать': 15, 'пытаешься': 36, 'ватник': 5, 'ли': 23}
(1, 60)
[[1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 1 1 1 3 3]]


In [51]:
y = train.toxic.values
y_test = test.toxic.values

In [52]:
clf = LogisticRegression(C=0.1, class_weight='balanced')
clf.fit(X, y)
clf.classes_

array([0., 1.])

In [67]:
preds = clf.predict(X)
preds

array([0., 0., 1., ..., 1., 0., 0.])

In [74]:
probas = clf.predict_proba(X)
probas

array([[9.76110315e-01, 2.38896852e-02],
       [5.36537894e-01, 4.63462106e-01],
       [3.35623640e-01, 6.64376360e-01],
       ...,
       [4.07948447e-01, 5.92051553e-01],
       [9.99856163e-01, 1.43836890e-04],
       [9.43440184e-01, 5.65598162e-02]])

In [94]:
clf = MultinomialNB(alpha=1.)
clf.fit(X, y)
preds = clf.predict(X)

print(classification_report(y, preds))

              precision    recall  f1-score   support

         0.0       0.97      0.98      0.98      8605
         1.0       0.96      0.94      0.95      4365

    accuracy                           0.97     12970
   macro avg       0.97      0.96      0.96     12970
weighted avg       0.97      0.97      0.97     12970



In [77]:
from sklearn.feature_extraction.text import CountVectorizer


text = ['''Верблюдов-то за что? Дебилы, бл...
",
"Хохлы, это отдушина затюканого россиянина, мол, вон, а у хохлов еще хуже. Если бы хохлов не было, кисель их бы придумал.
",
"Собаке - собачья смерть.
",
"Страницу обнови, дебил. Это тоже не оскорбление, а доказанный факт - не-дебил про себя во множественном числе писать не будет. Или мы в тебя верим - это ты и твои воображаемые друзья?
",
"тебя не убедил 6-страничный пдф в том, что Скрипалей отравила Россия? Анализировать и думать пытаешься? Ватник что ли?)
''']

vectorizer = TfidfVectorizer()
vectorizer.fit(text)

print(vectorizer.vocabulary_)


vector = vectorizer.transform(text)
print(vector.shape)
print(vector.toarray())

{'верблюдов': 6, 'то': 48, 'за': 18, 'что': 58, 'дебилы': 12, 'бл': 1, 'хохлы': 55, 'это': 59, 'отдушина': 30, 'затюканого': 19, 'россиянина': 38, 'мол': 25, 'вон': 9, 'хохлов': 54, 'еще': 17, 'хуже': 56, 'если': 16, 'бы': 3, 'не': 27, 'было': 4, 'кисель': 22, 'их': 21, 'придумал': 34, 'собаке': 42, 'собачья': 43, 'смерть': 41, 'страницу': 44, 'обнови': 28, 'дебил': 11, 'тоже': 49, 'оскорбление': 29, 'доказанный': 13, 'факт': 53, 'про': 35, 'себя': 39, 'во': 8, 'множественном': 24, 'числе': 57, 'писать': 33, 'будет': 2, 'или': 20, 'мы': 26, 'тебя': 47, 'верим': 7, 'ты': 51, 'твои': 46, 'воображаемые': 10, 'друзья': 14, 'убедил': 52, 'страничный': 45, 'пдф': 32, 'том': 50, 'скрипалей': 40, 'отравила': 31, 'россия': 37, 'анализировать': 0, 'думать': 15, 'пытаешься': 36, 'ватник': 5, 'ли': 23}
(1, 60)
[[0.09449112 0.09449112 0.09449112 0.18898224 0.09449112 0.09449112
  0.09449112 0.09449112 0.09449112 0.09449112 0.09449112 0.18898224
  0.09449112 0.09449112 0.09449112 0.09449112 0.094491

In [78]:
y = train.toxic.values
y_test = test.toxic.values

In [79]:
clf = LogisticRegression(C=0.1, class_weight='balanced')
clf.fit(X, y)
clf.classes_

array([0., 1.])

In [80]:
preds = clf.predict(X)
preds

array([0., 0., 1., ..., 1., 0., 0.])

In [81]:
probas = clf.predict_proba(X)
probas

array([[9.76110315e-01, 2.38896852e-02],
       [5.36537894e-01, 4.63462106e-01],
       [3.35623640e-01, 6.64376360e-01],
       ...,
       [4.07948447e-01, 5.92051553e-01],
       [9.99856163e-01, 1.43836890e-04],
       [9.43440184e-01, 5.65598162e-02]])

In [95]:
clf = MultinomialNB(alpha=1.)
clf.fit(X, y)
preds = clf.predict(X)

print(classification_report(y, preds))

              precision    recall  f1-score   support

         0.0       0.97      0.98      0.98      8605
         1.0       0.96      0.94      0.95      4365

    accuracy                           0.97     12970
   macro avg       0.97      0.96      0.96     12970
weighted avg       0.97      0.97      0.97     12970



# *Задание 4 (2 балла)

In [ ]:
Для классификаторов LogisticRegression, Decision Trees, Naive Bayes, Random Forest найдите способ извлечь важность признаков для предсказания токсичного класса. Сопоставьте полученные числа со словами (или нграммами) в словаре и найдите топ - 5 "токсичных" слов для каждого из классификаторов.

Важное требование: в топе не должно быть стоп-слов. Для этого вам нужно будет правильным образом настроить векторизацию.

In [ ]:
# ваш код